version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: deps
    command: pnpm dev
    depends_on:
      - mongodb
    environment:
      API_URL: http://localhost:3333
      MONGODB_URI: mongodb://mongodb:27017/rocketbox?retryWrites=true
      PORT: '3333'
    ports:
      - 3333:3333
    volumes:
      - ./backend/:/app/
      - /app/node_modules/

  frontend:
    build:
      context: ./frontend
      target: deps
    command: yarn dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend/:/app/
      - /app/node_modules/

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
